// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDJPYeAWOo4eP3vpt5lC8-3E9iKByzVys',
    appId: '1:22967815475:web:b51cbe201d1115bfc40246',
    messagingSenderId: '22967815475',
    projectId: 'prjpab2-si61-2327240004',
    authDomain: 'prjpab2-si61-2327240004.firebaseapp.com',
    storageBucket: 'prjpab2-si61-2327240004.firebasestorage.app',
    measurementId: 'G-SVVXGXB0NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt4z--3cY_lq51Sd_9NVqohu2c_gowxPM',
    appId: '1:22967815475:android:959ccca602b15db6c40246',
    messagingSenderId: '22967815475',
    projectId: 'prjpab2-si61-2327240004',
    storageBucket: 'prjpab2-si61-2327240004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxCCE0nYvvbCIwzOQrQZ5k4qMfXWlPwzU',
    appId: '1:22967815475:ios:dc85285f7259bb50c40246',
    messagingSenderId: '22967815475',
    projectId: 'prjpab2-si61-2327240004',
    storageBucket: 'prjpab2-si61-2327240004.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxCCE0nYvvbCIwzOQrQZ5k4qMfXWlPwzU',
    appId: '1:22967815475:ios:dc85285f7259bb50c40246',
    messagingSenderId: '22967815475',
    projectId: 'prjpab2-si61-2327240004',
    storageBucket: 'prjpab2-si61-2327240004.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDJPYeAWOo4eP3vpt5lC8-3E9iKByzVys',
    appId: '1:22967815475:web:b8356b24a9b6fc0ec40246',
    messagingSenderId: '22967815475',
    projectId: 'prjpab2-si61-2327240004',
    authDomain: 'prjpab2-si61-2327240004.firebaseapp.com',
    storageBucket: 'prjpab2-si61-2327240004.firebasestorage.app',
    measurementId: 'G-6W2D821ZK1',
  );
}
